#!/usr/bin/env python3
"""
Simple Backend Example for AI Dashboard
This is a minimal FastAPI backend that implements the required endpoints
for the YouTube summarizer to work.

Run this with: python simple-backend-example.py
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import uvicorn
import json

# Create FastAPI app
app = FastAPI(title="AI Dashboard Backend", version="1.0.0")

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:3001",
    ],
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["*"],
)

# Request/Response Models
class SummarizeRequest(BaseModel):
    content_type: str
    source: dict
    options: dict

class SummarizeResponse(BaseModel):
    summary: str
    metadata: dict
    source_info: dict

# Health endpoints
@app.get("/")
async def root():
    return {"message": "AI Dashboard Backend is running", "status": "ok"}

@app.get("/health")
async def health():
    return {
        "status": "healthy", 
        "timestamp": "2025-01-07T16:50:54Z",
        "version": "1.0.0"
    }

# Main summarize endpoint
@app.post("/api/summarize")
async def summarize(request: SummarizeRequest):
    """
    Main summarization endpoint that handles different content types
    """
    try:
        print(f"Received request: {request.content_type}")
        print(f"Source: {request.source}")
        print(f"Options: {request.options}")
        
        # Handle different content types
        if request.content_type == "link":
            return await handle_link_summarization(request)
        elif request.content_type == "text":
            return await handle_text_summarization(request)
        elif request.content_type == "file":
            return await handle_file_summarization(request)
        else:
            raise HTTPException(
                status_code=400, 
                detail=f"Unsupported content type: {request.content_type}"
            )
            
    except HTTPException:
        raise
    except Exception as e:
        print(f"Error in summarize endpoint: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")

async def handle_link_summarization(request: SummarizeRequest):
    """Handle YouTube URL summarization"""
    url = request.source.get("data", "")
    language = request.options.get("language", "en")
    mode = request.options.get("mode", "detailed")
    
    print(f"Processing YouTube URL: {url}")
    print(f"Language: {language}, Mode: {mode}")
    
    # Check if it's a YouTube URL
    if "youtube.com" not in url and "youtu.be" not in url:
        raise HTTPException(
            status_code=400, 
            detail="Only YouTube URLs are supported for link summarization"
        )
    
    # Simulate YouTube processing
    # In a real implementation, you would:
    # 1. Download the video/audio
    # 2. Extract transcript
    # 3. Use AI to generate summary
    
    # Mock response for testing
    mock_summary = f"""
# YouTube Video Summary

## Video Information
- **URL**: {url}
- **Language**: {language}
- **Processing Mode**: {mode}

## Summary
This is a mock summary for the YouTube video. In a real implementation, this would be generated by:

1. **Video Analysis**: Extracting key visual elements and scenes
2. **Audio Processing**: Converting speech to text using speech recognition
3. **AI Summarization**: Using language models to create concise summaries
4. **Key Points Extraction**: Identifying main topics and important moments

## Key Points
- This is a test video for demonstration purposes
- The video contains educational content about technology
- Main topics include AI, machine learning, and data science
- Duration: Approximately 10 minutes
- View count: 1,000,000+ views

## Timestamps
- 0:00 - Introduction
- 2:30 - Main topic discussion
- 5:45 - Key insights
- 8:20 - Conclusion

## Target Audience
This content is suitable for beginners interested in technology and AI.

## Educational Value
The video provides a comprehensive overview of modern technology trends and their impact on society.
"""
    
    return SummarizeResponse(
        summary=mock_summary.strip(),
        metadata={
            "content_type": "link",
            "processing_time": "5.2s",
            "tokens_used": 1500,
            "confidence": 0.95,
            "language": language,
            "mode": mode
        },
        source_info={
            "title": "Sample YouTube Video Title",
            "url": url,
            "author": "Sample Channel",
            "views": "1,000,000",
            "duration": "10:30",
            "published_date": "2025-01-01",
            "word_count": len(mock_summary.split())
        }
    )

async def handle_text_summarization(request: SummarizeRequest):
    """Handle text content summarization"""
    text = request.source.get("data", "")
    language = request.options.get("language", "en")
    
    print(f"Processing text content: {len(text)} characters")
    
    if not text.strip():
        raise HTTPException(status_code=400, detail="Empty text content")
    
    # Mock text summarization
    mock_summary = f"""
# Text Summary

## Content Analysis
- **Language**: {language}
- **Length**: {len(text)} characters
- **Word Count**: {len(text.split())} words

## Summary
This is a mock summary of the provided text content. The original text discusses various topics and provides valuable information for the reader.

## Key Points
- Main topic: Technology and innovation
- Key concepts: AI, machine learning, data science
- Target audience: General public
- Educational value: High

## Analysis
The content provides a comprehensive overview of modern technology trends and their impact on society. It covers various aspects including technical details, practical applications, and future implications.
"""
    
    return SummarizeResponse(
        summary=mock_summary.strip(),
        metadata={
            "content_type": "text",
            "processing_time": "2.1s",
            "tokens_used": 800,
            "confidence": 0.92,
            "language": language
        },
        source_info={
            "word_count": len(text.split()),
            "character_count": len(text),
            "language": language
        }
    )

async def handle_file_summarization(request: SummarizeRequest):
    """Handle file upload summarization"""
    file_id = request.source.get("data", "")
    
    print(f"Processing file: {file_id}")
    
    # Mock file processing
    mock_summary = f"""
# File Summary

## Document Information
- **File ID**: {file_id}
- **Type**: PDF Document
- **Pages**: 10
- **Size**: 2.5 MB

## Summary
This is a mock summary of the uploaded document. The document contains valuable information about various topics and provides comprehensive coverage of the subject matter.

## Key Topics
- Introduction to the subject
- Detailed analysis and discussion
- Practical applications
- Future implications
- Conclusion and recommendations

## Analysis
The document provides a thorough examination of the topic with detailed explanations, examples, and practical insights. It serves as a valuable resource for understanding the subject matter.
"""
    
    return SummarizeResponse(
        summary=mock_summary.strip(),
        metadata={
            "content_type": "file",
            "processing_time": "4.5s",
            "tokens_used": 2000,
            "confidence": 0.94
        },
        source_info={
            "file_id": file_id,
            "file_type": "pdf",
            "pages": 10,
            "word_count": 5000
        }
    )

# Additional endpoints for testing
@app.get("/api/health")
async def api_health():
    return {"status": "ok", "endpoint": "/api/health"}

@app.get("/docs")
async def docs():
    return {"message": "API documentation available at /docs"}

if __name__ == "__main__":
    print("🚀 Starting AI Dashboard Backend...")
    print("📡 Server will be available at: http://localhost:8000")
    print("📚 API docs will be available at: http://localhost:8000/docs")
    print("🔧 CORS configured for: http://localhost:3000")
    print("\n" + "="*50)
    
    uvicorn.run(
        app, 
        host="0.0.0.0", 
        port=8000, 
        log_level="info",
        reload=True
    )
